### ISSUE TITLE
Update to 115.15.0esr

### ISSUE THREAD

**Issue by Bungeetaco** [kawapure/firefox-native-controls#4]
xul.dll requires an update for 115.15.0esr

![firefox_PeIHMFZEOZ](https://github.com/user-attachments/assets/4ff9b49d-8023-4869-81e5-67e717db5e25)

**Comment by Bungeetaco** [comment]
Current rejects:

[https://pastebin.com/raw/0arvs0wu](https://pastebin.com/raw/0arvs0wu)

[https://pastebin.com/raw/GNzSqsPQ](https://pastebin.com/raw/GNzSqsPQ)

**Comment by kawapure** [comment]
You were not comparing between 115 subversions by the way, you were comparing between 115 and probably the current 129 beta. The diff will import into 115.15.0 just fine, as it does with all prior versions.

**Comment by Bungeetaco** [comment]
Sorry, I followed the following instructions from the README, but when I ran hg pull, it said no changes were made, so maybe I did it wrong:

> After cloning, navigate to .hg/hgrc in the source directory and change the default path to the branch of your preferred build. For example, I changed it to https://hg.mozilla.org/releases/mozilla-esr115 in order to access specific tags for the ESR 115 release. You can usually then find specific tags relating to subversions here: https://hg.mozilla.org/releases/mozilla-esr115/tags ("tags" tab in the Mercurial web viewer).
> 
> Since Firefox uses Mercurial for version control, it may be a little unfamiliar to you. You "update", rather than "checkout", different branches. So after you make those changes, I think you just do something like hg pull -u -r FIREFOX_115_3_1esr_RELEASE to switch to the specific branch. pull makes it get the specific version from remote, and -u means to update.

Thank you for updating the release! :)

**Comment by kawapure** [comment]
Yeah, Mercurial is really weird to work with. I think my workflow is `hg pull` and then run `hg update -r <commit ID>` separately. To be safe, I tend to clone the codebase again with every update because if changes linger from last time, then it could break compatibility for whatever reason.
